[WIP] Activity #1 Homework
Otus-Android/Basic-Activities pull request #21
Opened 2023-03-12 11:28 UTC by ProkofevDV

2023-03-19 07:37 UTC, antonkazakov requested changes
Привет. Оставил несколько комментариев, их нужно поправить

2023-03-19 07:37 UTC, antonkazakov commented on app/src/main/java/ru/otus/android/prokofyev/activities/ActivityA.kt
> +            val intentB = Intent(applicationContext, ActivityB::class.java)
А почему ты запускаешь именно с applicationContext? Он вообще может использоваться для открытия активити в новом стаке с флагом NEW_TASK, но у тебя, например, ActivityC должно открываться в том же стеке что и ActivityB

2023-03-19 07:37 UTC, antonkazakov commented on app/src/main/java/ru/otus/android/prokofyev/activities/ActivityB.kt
> +            val intentC = Intent(applicationContext, ActivityC::class.java)
Аналогично

2023-03-19 07:37 UTC, antonkazakov commented on app/src/main/java/ru/otus/android/prokofyev/activities/ActivityC.kt
> +            startActivity(intent)
Попробуй эту задачу решить без finishAffinity, достаточно запустить интент с нужными флагами

2023-03-20 07:37 UTC, ProkofevDV commented on app/src/main/java/ru/otus/android/prokofyev/activities/ActivityA.kt
> +            val intentB = Intent(applicationContext, ActivityB::class.java)
done

2023-03-20 07:37 UTC, ProkofevDV commented on app/src/main/java/ru/otus/android/prokofyev/activities/ActivityB.kt
> +            val intentC = Intent(applicationContext, ActivityC::class.java)
done

2023-03-20 07:37 UTC, ProkofevDV commented on app/src/main/java/ru/otus/android/prokofyev/activities/ActivityC.kt
> +            startActivity(intent)
done

2023-04-09 09:11 UTC, closed without merging